name = "kp"
compatibility_date = "2024-11-10"
main = "src/index.ts"

[observability]
enabled = true

# Cloudflare D1 Database
[[d1_databases]]
binding = "DB"
database_name = "kp-db"
database_id = "to-be-created"

# Cloudflare R2 Bucket
[[r2_buckets]]
binding = "R2"
bucket_name = "kp-audio"
